// SPDX-License-Identifier: GPL-3.0-or-later

import XCTest

@testable import SSHBorg

/// Parses keys produced by the real `ssh-keygen`.
///
/// The fixtures below were generated by OpenSSH, not by this project, which is
/// the point: a parser tested only against our own writer would agree with our
/// own mistakes. Together with the generator tests, which check the other
/// direction against `ssh-keygen -y`, both halves are pinned to the real thing.
///
/// These are throwaway keys that exist only in this file and were never
/// installed anywhere.
final class OpenSSHKeyImporterTests: XCTestCase {

    // MARK: - Fixtures

    private let ed25519Private = """
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACCyY6J65CDtrq2n39LhmES84B6gA6KT9rXfQ6l6lKcRjQAAAJhaD1dcWg9X
    XAAAAAtzc2gtZWQyNTUxOQAAACCyY6J65CDtrq2n39LhmES84B6gA6KT9rXfQ6l6lKcRjQ
    AAAECKIEAeElqY7A8whxC+VSqDHKT/CIOH8Yoom+jc9cpNkbJjonrkIO2uraff0uGYRLzg
    HqADopP2td9DqXqUpxGNAAAAD2ZpeHR1cmUtZWQyNTUxOQECAwQFBg==
    -----END OPENSSH PRIVATE KEY-----
    """

    private let ed25519Public =
        "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILJjonrkIO2uraff0uGYRLzgHqADopP2td9DqXqUpxGN fixture-ed25519"

    private let ecdsaPrivate = """
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAaAAAABNlY2RzYS
    1zaGEyLW5pc3RwMjU2AAAACG5pc3RwMjU2AAAAQQQ7JLNBBM0+3rTPQm+jCd+g9E2aWydb
    JMivqojjKMv3KCOpl3qZrGlUd+avDa0yij3kd76I48/GFr/MvczdlC7qAAAAqD6F2rQ+hd
    q0AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDsks0EEzT7etM9C
    b6MJ36D0TZpbJ1skyK+qiOMoy/coI6mXepmsaVR35q8NrTKKPeR3vojjz8YWv8y9zN2ULu
    oAAAAhAI3NLoT/C4E5Do5dnDfmwB9JOcFO/eRwBRxeMYGy/SsUAAAADWZpeHR1cmUtZWNk
    c2EBAg==
    -----END OPENSSH PRIVATE KEY-----
    """

    private let ecdsaPublic =
        "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDsks0EEzT7etM9Cb6MJ36D0TZpbJ1skyK+qiOMoy/coI6mXepmsaVR35q8NrTKKPeR3vojjz8YWv8y9zN2ULuo= fixture-ecdsa"

    // MARK: - Ed25519

    func testImportsEd25519FromSSHKeygen() throws {
        let imported = try OpenSSHKeyImporter.parse(ed25519Private)

        XCTAssertEqual(imported.type, .ed25519)
        XCTAssertEqual(imported.comment, "fixture-ed25519")

        // The derived public key must match, byte for byte, the .pub file
        // ssh-keygen wrote alongside it.
        XCTAssertEqual(imported.publicKeyLine, ed25519Public)
    }

    // MARK: - ECDSA

    func testImportsECDSAFromSSHKeygen() throws {
        let imported = try OpenSSHKeyImporter.parse(ecdsaPrivate)

        XCTAssertEqual(imported.type, .ecdsa)
        XCTAssertEqual(imported.comment, "fixture-ecdsa")
        XCTAssertEqual(imported.publicKeyLine, ecdsaPublic)
    }

    // MARK: - Round trip with our own generator

    /// Anything we write must be readable back, including the comment.
    func testImportsOurOwnKeys() throws {
        for type in SSHKey.KeyType.allCases {
            let generated = try SSHKeyGenerator.generate(
                type: type,
                bits: SSHKeyGenerator.defaultSize(for: type),
                comment: "round-trip"
            )
            let imported = try OpenSSHKeyImporter.parse(generated.privateKeyPEM)

            XCTAssertEqual(imported.type, type)
            XCTAssertEqual(imported.comment, "round-trip")
            XCTAssertEqual(imported.publicKeyLine, generated.publicKeyLine)
        }
    }

    // MARK: - Passphrase-protected keys

    /// Generated by `ssh-keygen -t ed25519 -N sshborg-test-pass`, so this is
    /// real OpenSSH output: aes256-ctr over a bcrypt-derived key.
    private let encryptedPrivate = """
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABC0Xwfw4v
    lJKDn148+Q/Q61AAAAGAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAIFpgB4BIgMx8yv8s
    b7JpQ8JwuZipvqJGXryWzQklBczWAAAAoBWS76rlF4Hus/N3QomgV3Z+egLClmcqERV1Ox
    dRbSUPCar65NBcfwFUdcth4mCEMQXUNVYSVNd0NoBJrt5gvdDh+y1KPy4EeQyUb3/AyEzD
    IGKnRYMOEKU8rB2xDxDqyVQCfCfWdYl0YVZr6ohDyld9sP9tKkHlnjCkgh0w9JoGBxfg4E
    ZSlRo0eFGqowrHxNyi9n44nZkIhL7RqdJjwMw=
    -----END OPENSSH PRIVATE KEY-----
    """

    private let encryptedPublic =
        "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFpgB4BIgMx8yv8sb7JpQ8JwuZipvqJGXryWzQklBczW fixture-encrypted"

    private let correctPassphrase = "sshborg-test-pass"

    /// The whole point of phase 5e: bcrypt_pbkdf comes from libssh2, and this
    /// proves it derives the same key OpenSSH did.
    func testDecryptsAPassphraseProtectedKey() throws {
        let imported = try OpenSSHKeyImporter.parse(encryptedPrivate, passphrase: correctPassphrase)

        XCTAssertEqual(imported.type, .ed25519)
        XCTAssertEqual(imported.comment, "fixture-encrypted")
        XCTAssertEqual(imported.publicKeyLine, encryptedPublic)
    }

    /// A wrong passphrase must say so, not report a damaged file: the user can
    /// act on the first and not on the second.
    func testWrongPassphraseIsNamedAsSuch() {
        XCTAssertThrowsError(
            try OpenSSHKeyImporter.parse(encryptedPrivate, passphrase: "not-the-passphrase")
        ) { error in
            XCTAssertEqual(error as? OpenSSHKeyImporter.ImportError, .wrongPassphrase)
        }
    }

    func testMissingPassphraseAsksForOne() {
        XCTAssertThrowsError(try OpenSSHKeyImporter.parse(encryptedPrivate)) { error in
            XCTAssertEqual(error as? OpenSSHKeyImporter.ImportError, .passphraseRequired)
        }

        XCTAssertThrowsError(
            try OpenSSHKeyImporter.parse(encryptedPrivate, passphrase: "")
        ) { error in
            XCTAssertEqual(error as? OpenSSHKeyImporter.ImportError, .passphraseRequired)
        }
    }

    /// A passphrase given for a key that has none is harmless, not an error.
    func testPassphraseOnAnUnencryptedKeyIsIgnored() throws {
        let imported = try OpenSSHKeyImporter.parse(ed25519Private, passphrase: "irrelevant")
        XCTAssertEqual(imported.publicKeyLine, ed25519Public)
    }

    // MARK: - Rejections

    func testLegacyEncryptedPEMIsNamedAsSuch() {
        let pem = """
        -----BEGIN RSA PRIVATE KEY-----
        Proc-Type: 4,ENCRYPTED
        DEK-Info: AES-128-CBC,0123456789ABCDEF

        AAAA
        -----END RSA PRIVATE KEY-----
        """

        XCTAssertThrowsError(try OpenSSHKeyImporter.parse(pem)) { error in
            XCTAssertEqual(error as? OpenSSHKeyImporter.ImportError, .legacyEncryptedPEM)
        }
    }

    /// Pasting the .pub file instead of the private one is an easy slip.
    func testPublicKeyIsRejectedWithAUsefulMessage() {
        XCTAssertThrowsError(try OpenSSHKeyImporter.parse(ed25519Public)) { error in
            XCTAssertEqual(error as? OpenSSHKeyImporter.ImportError, .notAPrivateKey)
        }
    }

    func testGarbageIsRejected() {
        XCTAssertThrowsError(try OpenSSHKeyImporter.parse("hello"))
        XCTAssertThrowsError(try OpenSSHKeyImporter.parse(""))
    }

    func testTruncatedKeyIsRejected() {
        let truncated = """
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAAB
        -----END OPENSSH PRIVATE KEY-----
        """

        XCTAssertThrowsError(try OpenSSHKeyImporter.parse(truncated))
    }

    /// A file saved on Windows must import just as well.
    func testCarriageReturnsAreTolerated() throws {
        let windowsStyle = ed25519Private.replacingOccurrences(of: "\n", with: "\r\n")
        let imported = try OpenSSHKeyImporter.parse(windowsStyle)
        XCTAssertEqual(imported.publicKeyLine, ed25519Public)
    }

    func testSurroundingWhitespaceIsTolerated() throws {
        let padded = "\n\n  \(ed25519Private)  \n\n"
        let imported = try OpenSSHKeyImporter.parse(padded)
        XCTAssertEqual(imported.type, .ed25519)
    }
}
