// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

import XCTest

@testable import SSHBorg

/// Parses keys produced by the real `ssh-keygen`.
///
/// The fixtures below were generated by OpenSSH, not by this project, which is
/// the point: a parser tested only against our own writer would agree with our
/// own mistakes. Together with the generator tests, which check the other
/// direction against `ssh-keygen -y`, both halves are pinned to the real thing.
///
/// These are throwaway keys that exist only in this file and were never
/// installed anywhere.
final class OpenSSHKeyImporterTests: XCTestCase {

    // MARK: - Fixtures

    private let ed25519Private = """
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACCyY6J65CDtrq2n39LhmES84B6gA6KT9rXfQ6l6lKcRjQAAAJhaD1dcWg9X
    XAAAAAtzc2gtZWQyNTUxOQAAACCyY6J65CDtrq2n39LhmES84B6gA6KT9rXfQ6l6lKcRjQ
    AAAECKIEAeElqY7A8whxC+VSqDHKT/CIOH8Yoom+jc9cpNkbJjonrkIO2uraff0uGYRLzg
    HqADopP2td9DqXqUpxGNAAAAD2ZpeHR1cmUtZWQyNTUxOQECAwQFBg==
    -----END OPENSSH PRIVATE KEY-----
    """

    private let ed25519Public =
        "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILJjonrkIO2uraff0uGYRLzgHqADopP2td9DqXqUpxGN fixture-ed25519"

    private let ecdsaPrivate = """
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAaAAAABNlY2RzYS
    1zaGEyLW5pc3RwMjU2AAAACG5pc3RwMjU2AAAAQQQ7JLNBBM0+3rTPQm+jCd+g9E2aWydb
    JMivqojjKMv3KCOpl3qZrGlUd+avDa0yij3kd76I48/GFr/MvczdlC7qAAAAqD6F2rQ+hd
    q0AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDsks0EEzT7etM9C
    b6MJ36D0TZpbJ1skyK+qiOMoy/coI6mXepmsaVR35q8NrTKKPeR3vojjz8YWv8y9zN2ULu
    oAAAAhAI3NLoT/C4E5Do5dnDfmwB9JOcFO/eRwBRxeMYGy/SsUAAAADWZpeHR1cmUtZWNk
    c2EBAg==
    -----END OPENSSH PRIVATE KEY-----
    """

    private let ecdsaPublic =
        "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDsks0EEzT7etM9Cb6MJ36D0TZpbJ1skyK+qiOMoy/coI6mXepmsaVR35q8NrTKKPeR3vojjz8YWv8y9zN2ULuo= fixture-ecdsa"

    // MARK: - Ed25519

    func testImportsEd25519FromSSHKeygen() throws {
        let imported = try OpenSSHKeyImporter.parse(ed25519Private)

        XCTAssertEqual(imported.type, .ed25519)
        XCTAssertEqual(imported.comment, "fixture-ed25519")

        // The derived public key must match, byte for byte, the .pub file
        // ssh-keygen wrote alongside it.
        XCTAssertEqual(imported.publicKeyLine, ed25519Public)
    }

    // MARK: - ECDSA

    func testImportsECDSAFromSSHKeygen() throws {
        let imported = try OpenSSHKeyImporter.parse(ecdsaPrivate)

        XCTAssertEqual(imported.type, .ecdsa)
        XCTAssertEqual(imported.comment, "fixture-ecdsa")
        XCTAssertEqual(imported.publicKeyLine, ecdsaPublic)
    }

    // MARK: - Round trip with our own generator

    /// Anything we write must be readable back, including the comment.
    func testImportsOurOwnKeys() throws {
        for type in SSHKey.KeyType.allCases {
            let generated = try SSHKeyGenerator.generate(
                type: type,
                bits: SSHKeyGenerator.defaultSize(for: type),
                comment: "round-trip"
            )
            let imported = try OpenSSHKeyImporter.parse(generated.privateKeyPEM)

            XCTAssertEqual(imported.type, type)
            XCTAssertEqual(imported.comment, "round-trip")
            XCTAssertEqual(imported.publicKeyLine, generated.publicKeyLine)
        }
    }

    // MARK: - Rejections

    /// A passphrase-protected key must say so plainly rather than fail as
    /// "damaged": the user can act on the first message and not the second.
    func testPassphraseProtectedKeyIsNamedAsSuch() throws {
        // ciphername and kdfname set to something other than "none".
        var body = SSHWireEncoder()
        body.write(raw: Data("openssh-key-v1\0".utf8))
        body.write(string: "aes256-ctr")
        body.write(string: "bcrypt")
        body.write(string: Data([0x01]))
        body.write(uint32: 1)
        body.write(string: Data([0x02]))
        body.write(string: Data([0x03]))

        let pem = SSHKeyGenerator.armour(body.data)

        XCTAssertThrowsError(try OpenSSHKeyImporter.parse(pem)) { error in
            XCTAssertEqual(error as? OpenSSHKeyImporter.ImportError, .passphraseProtected)
        }
    }

    func testLegacyEncryptedPEMIsNamedAsSuch() {
        let pem = """
        -----BEGIN RSA PRIVATE KEY-----
        Proc-Type: 4,ENCRYPTED
        DEK-Info: AES-128-CBC,0123456789ABCDEF

        AAAA
        -----END RSA PRIVATE KEY-----
        """

        XCTAssertThrowsError(try OpenSSHKeyImporter.parse(pem)) { error in
            XCTAssertEqual(error as? OpenSSHKeyImporter.ImportError, .passphraseProtected)
        }
    }

    /// Pasting the .pub file instead of the private one is an easy slip.
    func testPublicKeyIsRejectedWithAUsefulMessage() {
        XCTAssertThrowsError(try OpenSSHKeyImporter.parse(ed25519Public)) { error in
            XCTAssertEqual(error as? OpenSSHKeyImporter.ImportError, .notAPrivateKey)
        }
    }

    func testGarbageIsRejected() {
        XCTAssertThrowsError(try OpenSSHKeyImporter.parse("hello"))
        XCTAssertThrowsError(try OpenSSHKeyImporter.parse(""))
    }

    func testTruncatedKeyIsRejected() {
        let truncated = """
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAAB
        -----END OPENSSH PRIVATE KEY-----
        """

        XCTAssertThrowsError(try OpenSSHKeyImporter.parse(truncated))
    }

    /// A file saved on Windows must import just as well.
    func testCarriageReturnsAreTolerated() throws {
        let windowsStyle = ed25519Private.replacingOccurrences(of: "\n", with: "\r\n")
        let imported = try OpenSSHKeyImporter.parse(windowsStyle)
        XCTAssertEqual(imported.publicKeyLine, ed25519Public)
    }

    func testSurroundingWhitespaceIsTolerated() throws {
        let padded = "\n\n  \(ed25519Private)  \n\n"
        let imported = try OpenSSHKeyImporter.parse(padded)
        XCTAssertEqual(imported.type, .ed25519)
    }
}
