// SPDX-License-Identifier: GPL-3.0-or-later
//
// Generated by scripts/import-android-strings.py — do not edit.
//
// The keys are the Android app's, verbatim, so the two catalogues can be
// diffed by key when the Android side gains or changes a string.

import Foundation

extension LocalizedStringResource {

    /// Licence
    static let aboutLicence = LocalizedStringResource("about_licence")

    /// About
    static let aboutSectionTitle = LocalizedStringResource("about_section_title")

    /// Version
    static let aboutVersion = LocalizedStringResource("about_version")

    /// Accept
    static let actionAccept = LocalizedStringResource("action_accept")

    /// Back
    static let actionBack = LocalizedStringResource("action_back")

    /// Cancel
    static let actionCancel = LocalizedStringResource("action_cancel")

    /// Close
    static let actionClose = LocalizedStringResource("action_close")

    /// Connect
    static let actionConnect = LocalizedStringResource("action_connect")

    /// Copied!
    static let actionCopied = LocalizedStringResource("action_copied")

    /// Copy
    static let actionCopy = LocalizedStringResource("action_copy")

    /// Create
    static let actionCreate = LocalizedStringResource("action_create")

    /// Delete
    static let actionDelete = LocalizedStringResource("action_delete")

    /// Delete all
    static let actionDeleteAll = LocalizedStringResource("action_delete_all")

    /// Done
    static let actionDone = LocalizedStringResource("action_done")

    /// Don't show again
    static let actionDontShowAgain = LocalizedStringResource("action_dont_show_again")

    /// Duplicate
    static let actionDuplicate = LocalizedStringResource("action_duplicate")

    /// Edit
    static let actionEdit = LocalizedStringResource("action_edit")

    /// Enable
    static let actionEnable = LocalizedStringResource("action_enable")

    /// Generate
    static let actionGenerate = LocalizedStringResource("action_generate")

    /// Go back
    static let actionGoBack = LocalizedStringResource("action_go_back")

    /// Hide
    static let actionHide = LocalizedStringResource("action_hide")

    /// I understand
    static let actionIUnderstand = LocalizedStringResource("action_i_understand")

    /// Keep both
    static let actionKeepBoth = LocalizedStringResource("action_keep_both")

    /// Overwrite
    static let actionOverwrite = LocalizedStringResource("action_overwrite")

    /// Overwrite all
    static let actionOverwriteAll = LocalizedStringResource("action_overwrite_all")

    /// Read Policy
    static let actionReadPolicy = LocalizedStringResource("action_read_policy")

    /// Reject
    static let actionReject = LocalizedStringResource("action_reject")

    /// Remind me later
    static let actionRemindLater = LocalizedStringResource("action_remind_later")

    /// Rename
    static let actionRename = LocalizedStringResource("action_rename")

    /// Save
    static let actionSave = LocalizedStringResource("action_save")

    /// Show
    static let actionShow = LocalizedStringResource("action_show")

    /// Skip existing
    static let actionSkipExisting = LocalizedStringResource("action_skip_existing")

    /// Trust
    static let actionTrust = LocalizedStringResource("action_trust")

    /// Add Host
    static let addHostTitle = LocalizedStringResource("add_host_title")

    /// SSHBorg
    static let appName = LocalizedStringResource("app_name")

    /// Exported %1$d hosts
    static let backupExportSuccess = LocalizedStringResource("backup_export_success")

    /// Imported %1$d, updated %2$d hosts
    static let backupImportSuccess = LocalizedStringResource("backup_import_success")

    /// Authenticate to continue
    static let biometricPromptSubtitle = LocalizedStringResource("biometric_prompt_subtitle")

    /// SSHBorg
    static let biometricPromptTitle = LocalizedStringResource("biometric_prompt_title")

    /// Edit Host
    static let editHostTitle = LocalizedStringResource("edit_host_title")

    /// Cannot list directory
    static let errorCannotListDirectory = LocalizedStringResource("error_cannot_list_directory")

    /// Connection failed
    static let errorConnectionFailed = LocalizedStringResource("error_connection_failed")

    /// Create directory failed
    static let errorCreateDirectoryFailed = LocalizedStringResource("error_create_directory_failed")

    /// Decryption failed
    static let errorDecryptionFailed = LocalizedStringResource("error_decryption_failed")

    /// Delete failed
    static let errorDeleteFailed = LocalizedStringResource("error_delete_failed")

    /// Download failed
    static let errorDownloadFailed = LocalizedStringResource("error_download_failed")

    /// Encryption failed
    static let errorEncryptionFailed = LocalizedStringResource("error_encryption_failed")

    /// Host not found
    static let errorHostNotFound = LocalizedStringResource("error_host_not_found")

    /// Refresh failed
    static let errorRefreshFailed = LocalizedStringResource("error_refresh_failed")

    /// Rename failed
    static let errorRenameFailed = LocalizedStringResource("error_rename_failed")

    /// Session not found
    static let errorSessionNotFound = LocalizedStringResource("error_session_not_found")

    /// Something went wrong
    static let errorUnknown = LocalizedStringResource("error_unknown")

    /// Upload failed
    static let errorUploadFailed = LocalizedStringResource("error_upload_failed")

    /// Delete "%1$@"? Its hosts will be kept, without a group.
    static let groupDeleteMessage = LocalizedStringResource("group_delete_message")

    /// Delete group
    static let groupDeleteTitle = LocalizedStringResource("group_delete_title")

    /// Name
    static let groupDialogName = LocalizedStringResource("group_dialog_name")

    /// Edit group
    static let groupDialogTitleEdit = LocalizedStringResource("group_dialog_title_edit")

    /// New group
    static let groupDialogTitleNew = LocalizedStringResource("group_dialog_title_new")

    /// Agent Forwarding
    static let hostAgentForwarding = LocalizedStringResource("host_agent_forwarding")

    /// Allow Legacy Ciphers
    static let hostAllowLegacyCiphers = LocalizedStringResource("host_allow_legacy_ciphers")

    /// Password
    static let hostAuthPassword = LocalizedStringResource("host_auth_password")

    /// SSH Key
    static let hostAuthSshKey = LocalizedStringResource("host_auth_ssh_key")

    /// %1$@ (copy)
    static let hostCloneLabel = LocalizedStringResource("host_clone_label")

    /// Automatic
    static let hostColorAuto = LocalizedStringResource("host_color_auto")

    /// Custom
    static let hostColorCustom = LocalizedStringResource("host_color_custom")

    /// Host color
    static let hostColorDialogTitle = LocalizedStringResource("host_color_dialog_title")

    /// Color
    static let hostColorLabel = LocalizedStringResource("host_color_label")

    /// Remove custom color
    static let hostColorRemove = LocalizedStringResource("host_color_remove")

    /// Hostname / IP
    static let hostFieldHostname = LocalizedStringResource("host_field_hostname")

    /// Jump hosts (-J)
    static let hostFieldJumpHosts = LocalizedStringResource("host_field_jump_hosts")

    /// Label (optional)
    static let hostFieldLabel = LocalizedStringResource("host_field_label")

    /// Password
    static let hostFieldPassword = LocalizedStringResource("host_field_password")

    /// Port
    static let hostFieldPort = LocalizedStringResource("host_field_port")

    /// Forwarding rules (-L)
    static let hostFieldPortForwarding = LocalizedStringResource("host_field_port_forwarding")

    /// Starting directory
    static let hostFieldStartDirectory = LocalizedStringResource("host_field_start_directory")

    /// Username
    static let hostFieldUsername = LocalizedStringResource("host_field_username")

    /// Group
    static let hostGroupLabel = LocalizedStringResource("host_group_label")

    /// New group…
    static let hostGroupNew = LocalizedStringResource("host_group_new")

    /// No group
    static let hostGroupNone = LocalizedStringResource("host_group_none")

    /// Add jump host
    static let hostJumpAdd = LocalizedStringResource("host_jump_add")

    /// host1:22,user@host2:2222
    static let hostJumpHostsPlaceholder = LocalizedStringResource("host_jump_hosts_placeholder")

    /// Comma-separated: [user@]host[:port] — defaults: port 22, same user
    static let hostJumpHostsSupporting = LocalizedStringResource("host_jump_hosts_supporting")

    /// Host list
    static let hostJumpModeHostList = LocalizedStringResource("host_jump_mode_host_list")

    /// Simple
    static let hostJumpModeSimple = LocalizedStringResource("host_jump_mode_simple")

    /// No saved password
    static let hostJumpNoPassword = LocalizedStringResource("host_jump_no_password")

    /// Select host…
    static let hostJumpSelectPlaceholder = LocalizedStringResource("host_jump_select_placeholder")

    /// Change
    static let hostKeyChange = LocalizedStringResource("host_key_change")

    /// No keys – go add one first
    static let hostKeyNoKeys = LocalizedStringResource("host_key_no_keys")

    /// Select a key…
    static let hostKeySelectPlaceholder = LocalizedStringResource("host_key_select_placeholder")

    /// Connect
    static let hostMenuConnect = LocalizedStringResource("host_menu_connect")

    /// Files
    static let hostMenuFiles = LocalizedStringResource("host_menu_files")

    /// New files session
    static let hostMenuNewFilesSession = LocalizedStringResource("host_menu_new_files_session")

    /// New terminal
    static let hostMenuNewTerminal = LocalizedStringResource("host_menu_new_terminal")

    /// Resume files (%1$d)
    static let hostMenuResumeFiles = LocalizedStringResource("host_menu_resume_files")

    /// Resume terminal (%1$d)
    static let hostMenuResumeTerminal = LocalizedStringResource("host_menu_resume_terminal")

    /// 8080:localhost:8080 bindAddr:8443:server:443
    static let hostPortForwardingPlaceholder = LocalizedStringResource("host_port_forwarding_placeholder")

    /// One rule per line: [localPort:remoteHost:remotePort] or [bindAddr:localPort:remoteHos…
    static let hostPortForwardingSupporting = LocalizedStringResource("host_port_forwarding_supporting")

    /// Reset accepted host keys
    static let hostResetHostKeys = LocalizedStringResource("host_reset_host_keys")

    /// Forgets the saved host key and cached jump-host keys. The next connection will verify…
    static let hostResetHostKeysHint = LocalizedStringResource("host_reset_host_keys_hint")

    /// Host keys will be reset on save
    static let hostResetHostKeysPending = LocalizedStringResource("host_reset_host_keys_pending")

    /// Authentication
    static let hostSectionAuthentication = LocalizedStringResource("host_section_authentication")

    /// Jump Hosts
    static let hostSectionJumpHosts = LocalizedStringResource("host_section_jump_hosts")

    /// Port Forwarding
    static let hostSectionPortForwarding = LocalizedStringResource("host_section_port_forwarding")

    /// SFTP: Starting Directory
    static let hostSectionStartDirectory = LocalizedStringResource("host_section_start_directory")

    /// Fixed folder
    static let hostStartModeFixed = LocalizedStringResource("host_start_mode_fixed")

    /// Home
    static let hostStartModeHome = LocalizedStringResource("host_start_mode_home")

    /// Last visited folder
    static let hostStartModeLast = LocalizedStringResource("host_start_mode_last")

    /// %1$@  %2$@  Connect anyway?
    static let hostkeySftpBody = LocalizedStringResource("hostkey_sftp_body")

    /// Fingerprint:
    static let hostkeyTerminalFingerprint = LocalizedStringResource("hostkey_terminal_fingerprint")

    /// Host: %1$@
    static let hostkeyTerminalHost = LocalizedStringResource("hostkey_terminal_host")

    /// Do you trust this host?
    static let hostkeyTerminalTrustQuestion = LocalizedStringResource("hostkey_terminal_trust_question")

    /// Unknown host
    static let hostkeyTitle = LocalizedStringResource("hostkey_title")

    /// Add host
    static let hostsAddHostCd = LocalizedStringResource("hosts_add_host_cd")

    /// Delete "%1$@"?
    static let hostsDeleteMessage = LocalizedStringResource("hosts_delete_message")

    /// Delete host
    static let hostsDeleteTitle = LocalizedStringResource("hosts_delete_title")

    /// No hosts yet. Tap + to add one.
    static let hostsEmpty = LocalizedStringResource("hosts_empty")

    /// Help
    static let hostsHelpCd = LocalizedStringResource("hosts_help_cd")

    /// Manage keys
    static let hostsManageKeysCd = LocalizedStringResource("hosts_manage_keys_cd")

    /// Options
    static let hostsOptionsCd = LocalizedStringResource("hosts_options_cd")

    /// Press back again to exit
    static let hostsPressBackToExit = LocalizedStringResource("hosts_press_back_to_exit")

    /// Settings
    static let hostsSettingsCd = LocalizedStringResource("hosts_settings_cd")

    /// SSHBorg
    static let hostsTitle = LocalizedStringResource("hosts_title")

    /// Add
    static let iosActionAdd = LocalizedStringResource("ios_action_add")

    /// Reconnect
    static let iosActionReconnect = LocalizedStringResource("ios_action_reconnect")

    /// Retry
    static let iosActionRetry = LocalizedStringResource("ios_action_retry")

    /// Stop
    static let iosActionStop = LocalizedStringResource("ios_action_stop")

    /// Could not save
    static let iosErrorSaveFailed = LocalizedStringResource("ios_error_save_failed")

    /// %1$d port forwarding rules are not active
    static let iosForwardingInactiveMany = LocalizedStringResource("ios_forwarding_inactive_many")

    /// A port forwarding rule is not active
    static let iosForwardingInactiveOne = LocalizedStringResource("ios_forwarding_inactive_one")

    /// Colour
    static let iosGroupColour = LocalizedStringResource("ios_group_colour")

    /// Hide keyboard
    static let iosHideKeyboard = LocalizedStringResource("ios_hide_keyboard")

    /// Without a colour of its own, a host takes its group's.
    static let iosHostColourFooter = LocalizedStringResource("ios_host_colour_footer")

    /// %1$d hosts are not listed because they have no saved password or key, which a hop can…
    static let iosHostHiddenCandidates = LocalizedStringResource("ios_host_hidden_candidates")

    /// Hop %1$d
    static let iosHostHopNumber = LocalizedStringResource("ios_host_hop_number")

    /// Legacy ciphers let you reach old servers, at the cost of weaker cryptography. Leave o…
    static let iosHostLegacyFooter = LocalizedStringResource("ios_host_legacy_footer")

    /// No other host has a saved credential to use as a hop.
    static let iosHostNoJumpCandidates = LocalizedStringResource("ios_host_no_jump_candidates")

    /// Host key changed
    static let iosHostkeyChangedTitle = LocalizedStringResource("ios_hostkey_changed_title")

    /// Left blank, the key's own comment is used.
    static let iosKeysCommentBlank = LocalizedStringResource("ios_keys_comment_blank")

    /// Created
    static let iosKeysCreated = LocalizedStringResource("ios_keys_created")

    /// %1$@ is used by %2$d hosts. They will be kept but fall back to password authenticatio…
    static let iosKeysDeleteImpact = LocalizedStringResource("ios_keys_delete_impact")

    /// Generate a key, or import one you already use.
    static let iosKeysEmptyHint = LocalizedStringResource("ios_keys_empty_hint")

    /// Fingerprint
    static let iosKeysFingerprint = LocalizedStringResource("ios_keys_fingerprint")

    /// Also stored as the key's comment, which is what a server shows in its logs.
    static let iosKeysLabelFooter = LocalizedStringResource("ios_keys_label_footer")

    /// Stored
    static let iosKeysStored = LocalizedStringResource("ios_keys_stored")

    /// Type
    static let iosKeysType = LocalizedStringResource("ios_keys_type")

    /// Enter the password for %1$@.
    static let iosPasswordPrompt = LocalizedStringResource("ios_password_prompt")

    /// Actions
    static let iosSftpActions = LocalizedStringResource("ios_sftp_actions")

    /// %1$@ already exists here. Keeping both saves it as %2$@.
    static let iosSftpConflictDetail = LocalizedStringResource("ios_sftp_conflict_detail")

    /// Upload…
    static let iosSftpUpload = LocalizedStringResource("ios_sftp_upload")

    /// Connecting to %1$@…
    static let iosTerminalConnecting = LocalizedStringResource("ios_terminal_connecting")

    /// No open sessions
    static let iosTerminalNoSessions = LocalizedStringResource("ios_terminal_no_sessions")

    /// Connect to a host to open a terminal.
    static let iosTerminalNoSessionsHint = LocalizedStringResource("ios_terminal_no_sessions_hint")

    /// reconnected — this is a new shell
    static let iosTerminalReconnected = LocalizedStringResource("ios_terminal_reconnected")

    /// Clear finished
    static let iosTransfersClear = LocalizedStringResource("ios_transfers_clear")

    /// Transfers
    static let iosTransfersTitle = LocalizedStringResource("ios_transfers_title")

    /// Word suggestions
    static let iosWordMode = LocalizedStringResource("ios_word_mode")

    /// Curve (bit)
    static let keygenCurveBits = LocalizedStringResource("keygen_curve_bits")

    /// Label
    static let keygenFieldLabel = LocalizedStringResource("keygen_field_label")

    /// Fixed size: 256 bit
    static let keygenFixedSize = LocalizedStringResource("keygen_fixed_size")

    /// Key type
    static let keygenKeyType = LocalizedStringResource("keygen_key_type")

    /// Size (bit)
    static let keygenSizeBits = LocalizedStringResource("keygen_size_bits")

    /// Generate SSH Key
    static let keygenTitle = LocalizedStringResource("keygen_title")

    /// Delete
    static let keysDeleteCd = LocalizedStringResource("keys_delete_cd")

    /// Delete "%1$@"? Any hosts using this key will fall back to password auth.
    static let keysDeleteMessage = LocalizedStringResource("keys_delete_message")

    /// Delete key
    static let keysDeleteTitle = LocalizedStringResource("keys_delete_title")

    /// The private key cannot be recovered once deleted.
    static let keysDeleteWarning = LocalizedStringResource("keys_delete_warning")

    /// No keys yet. Tap + to generate one.
    static let keysEmpty = LocalizedStringResource("keys_empty")

    /// Generate key
    static let keysGenerateCd = LocalizedStringResource("keys_generate_cd")

    /// Import
    static let keysImportAction = LocalizedStringResource("keys_import_action")

    /// Import key
    static let keysImportCd = LocalizedStringResource("keys_import_cd")

    /// Imported Key
    static let keysImportDefaultLabel = LocalizedStringResource("keys_import_default_label")

    /// This key is encrypted — enter the passphrase
    static let keysImportErrorEncrypted = LocalizedStringResource("keys_import_error_encrypted")

    /// Invalid or unsupported key format
    static let keysImportErrorInvalid = LocalizedStringResource("keys_import_error_invalid")

    /// Wrong passphrase
    static let keysImportErrorWrongPassphrase = LocalizedStringResource("keys_import_error_wrong_passphrase")

    /// Load from file
    static let keysImportLoadFromFile = LocalizedStringResource("keys_import_load_from_file")

    /// Passphrase (if encrypted)
    static let keysImportPassphraseLabel = LocalizedStringResource("keys_import_passphrase_label")

    /// Private key (PEM / OpenSSH format)
    static let keysImportPemLabel = LocalizedStringResource("keys_import_pem_label")

    /// Import SSH Key
    static let keysImportTitle = LocalizedStringResource("keys_import_title")

    /// Public key (add to ~/.ssh/authorized_keys):
    static let keysPublicKeyLabel = LocalizedStringResource("keys_public_key_label")

    /// Rename
    static let keysRenameCd = LocalizedStringResource("keys_rename_cd")

    /// Rename key
    static let keysRenameTitle = LocalizedStringResource("keys_rename_title")

    /// Show public key
    static let keysShowPublicKeyCd = LocalizedStringResource("keys_show_public_key_cd")

    /// SSH Keys
    static let keysTitle = LocalizedStringResource("keys_title")

    /// %d active sessions
    static let notificationActiveSessions = LocalizedStringResource("notification_active_sessions")

    /// %d files downloading
    static let notificationBgDownloads = LocalizedStringResource("notification_bg_downloads")

    /// Android reached its limit on how long the app can run in the background, so your sess…
    static let notificationBgTimeoutText = LocalizedStringResource("notification_bg_timeout_text")

    /// Sessions stopped
    static let notificationBgTimeoutTitle = LocalizedStringResource("notification_bg_timeout_title")

    /// Shows active SSH/SFTP sessions
    static let notificationChannelDescription = LocalizedStringResource("notification_channel_description")

    /// Active SSH sessions
    static let notificationChannelName = LocalizedStringResource("notification_channel_name")

    /// Notifications when file transfers complete
    static let notificationChannelTransfersDescription = LocalizedStringResource("notification_channel_transfers_description")

    /// File transfers
    static let notificationChannelTransfersName = LocalizedStringResource("notification_channel_transfers_name")

    /// Disconnect all
    static let notificationDisconnectAll = LocalizedStringResource("notification_disconnect_all")

    /// No active sessions
    static let notificationNoSessions = LocalizedStringResource("notification_no_sessions")

    /// Authentication failed. Please try again.
    static let passwordAuthFailed = LocalizedStringResource("password_auth_failed")

    /// Password for %1$@
    static let passwordDialogTitle = LocalizedStringResource("password_dialog_title")

    /// Password
    static let passwordFieldLabel = LocalizedStringResource("password_field_label")

    /// Before using SSHBorg, please review our Privacy Policy. SSHBorg stores all data local…
    static let privacyPolicyDialogBody = LocalizedStringResource("privacy_policy_dialog_body")

    /// Privacy Policy
    static let privacyPolicyDialogTitle = LocalizedStringResource("privacy_policy_dialog_title")

    /// This device appears to be rooted. On rooted devices the security guarantees of the An…
    static let rootWarningBody = LocalizedStringResource("root_warning_body")

    /// Security warning
    static let rootWarningTitle = LocalizedStringResource("root_warning_title")

    /// Enable an app lock and hardware encryption in Settings to keep your credentials safe.
    static let securityReminderBody = LocalizedStringResource("security_reminder_body")

    /// Security tip
    static let securityReminderTitle = LocalizedStringResource("security_reminder_title")

    /// New %1$@ session
    static let sessionPickerNewSession = LocalizedStringResource("session_picker_new_session")

    /// Session %1$d
    static let sessionPickerSessionLabel = LocalizedStringResource("session_picker_session_label")

    /// %1$@ — %2$@ sessions
    static let sessionPickerTitle = LocalizedStringResource("session_picker_title")

    /// Connected
    static let sessionStatusConnected = LocalizedStringResource("session_status_connected")

    /// Connecting…
    static let sessionStatusConnecting = LocalizedStringResource("session_status_connecting")

    /// Disconnected
    static let sessionStatusDisconnected = LocalizedStringResource("session_status_disconnected")

    /// Error
    static let sessionStatusError = LocalizedStringResource("session_status_error")

    /// Files
    static let sessionTypeFiles = LocalizedStringResource("session_type_files")

    /// Terminal
    static let sessionTypeTerminal = LocalizedStringResource("session_type_terminal")

    /// Permit screenshots and screen recording. Leave disabled to protect sensitive content.
    static let settingsAllowScreenshotsSubtitle = LocalizedStringResource("settings_allow_screenshots_subtitle")

    /// Allow screenshots
    static let settingsAllowScreenshotsTitle = LocalizedStringResource("settings_allow_screenshots_title")

    /// App lock
    static let settingsAppLockTitle = LocalizedStringResource("settings_app_lock_title")

    /// Export
    static let settingsBackupExportAction = LocalizedStringResource("settings_backup_export_action")

    /// Save host configurations and app settings to a JSON file. Passwords and keys are not …
    static let settingsBackupExportSubtitle = LocalizedStringResource("settings_backup_export_subtitle")

    /// Export backup
    static let settingsBackupExportTitle = LocalizedStringResource("settings_backup_export_title")

    /// Import
    static let settingsBackupImportAction = LocalizedStringResource("settings_backup_import_action")

    /// Load host configurations and app settings from a JSON file. Existing hosts with the s…
    static let settingsBackupImportSubtitle = LocalizedStringResource("settings_backup_import_subtitle")

    /// Import backup
    static let settingsBackupImportTitle = LocalizedStringResource("settings_backup_import_title")

    /// Require authentication when returning to the app
    static let settingsBiometricAvailable = LocalizedStringResource("settings_biometric_available")

    /// Biometric lock
    static let settingsBiometricLockTitle = LocalizedStringResource("settings_biometric_lock_title")

    /// No biometric or screen lock set up on this device
    static let settingsBiometricUnavailable = LocalizedStringResource("settings_biometric_unavailable")

    /// Ask for confirmation before closing the app
    static let settingsConfirmExitSubtitle = LocalizedStringResource("settings_confirm_exit_subtitle")

    /// Confirm exit
    static let settingsConfirmExitTitle = LocalizedStringResource("settings_confirm_exit_title")

    /// Nothing
    static let settingsDoubleTapNone = LocalizedStringResource("settings_double_tap_none")

    /// What a double-tap on the terminal sends to the shell
    static let settingsDoubleTapSubtitle = LocalizedStringResource("settings_double_tap_subtitle")

    /// Send Tab
    static let settingsDoubleTapTab = LocalizedStringResource("settings_double_tap_tab")

    /// Send Tab twice
    static let settingsDoubleTapTabTwice = LocalizedStringResource("settings_double_tap_tab_twice")

    /// Double-tap action
    static let settingsDoubleTapTitle = LocalizedStringResource("settings_double_tap_title")

    /// Your SSH private keys and host passwords will be encrypted using this device's secure…
    static let settingsEncryptDialogBody = LocalizedStringResource("settings_encrypt_dialog_body")

    /// Encrypt sensitive data?
    static let settingsEncryptDialogTitle = LocalizedStringResource("settings_encrypt_dialog_title")

    /// SSH private keys and host passwords are encrypted using this device's secure hardware…
    static let settingsEncryptSubtitle = LocalizedStringResource("settings_encrypt_subtitle")

    /// Encrypt sensitive data
    static let settingsEncryptTitle = LocalizedStringResource("settings_encrypt_title")

    /// Keep the extra key bar (Ctrl, arrows, F-keys…) visible even when the keyboard is clos…
    static let settingsExtraKeysBarSubtitle = LocalizedStringResource("settings_extra_keys_bar_subtitle")

    /// Always-visible extra keys
    static let settingsExtraKeysBarTitle = LocalizedStringResource("settings_extra_keys_bar_title")

    /// Default terminal text size (sp); pinch to zoom in a session
    static let settingsFontSizeSubtitle = LocalizedStringResource("settings_font_size_subtitle")

    /// Font size
    static let settingsFontSizeTitle = LocalizedStringResource("settings_font_size_title")

    /// Show suggestions from the server shell history while typing in the terminal
    static let settingsHistorySuggestionsSubtitle = LocalizedStringResource("settings_history_suggestions_subtitle")

    /// Command history suggestions
    static let settingsHistorySuggestionsTitle = LocalizedStringResource("settings_history_suggestions_title")

    /// Swipe up to see older output instead of newer
    static let settingsInvertScrollSubtitle = LocalizedStringResource("settings_invert_scroll_subtitle")

    /// Invert terminal scroll
    static let settingsInvertScrollTitle = LocalizedStringResource("settings_invert_scroll_title")

    /// Prevent the screen from turning off while a terminal is open
    static let settingsKeepScreenOnSubtitle = LocalizedStringResource("settings_keep_screen_on_subtitle")

    /// Keep screen on
    static let settingsKeepScreenOnTitle = LocalizedStringResource("settings_keep_screen_on_title")

    /// Language
    static let settingsLanguage = LocalizedStringResource("settings_language")

    /// System default
    static let settingsLanguageSystem = LocalizedStringResource("settings_language_system")

    /// Time before requiring authentication again
    static let settingsLockAfterSubtitle = LocalizedStringResource("settings_lock_after_subtitle")

    /// Lock after
    static let settingsLockAfterTitle = LocalizedStringResource("settings_lock_after_title")

    /// Biometric only
    static let settingsLockModeBiometric = LocalizedStringResource("settings_lock_mode_biometric")

    /// Device lock (PIN or biometric)
    static let settingsLockModeDevice = LocalizedStringResource("settings_lock_mode_device")

    /// None
    static let settingsLockModeNone = LocalizedStringResource("settings_lock_mode_none")

    /// %1$d seconds
    static let settingsLockTimeoutFallback = LocalizedStringResource("settings_lock_timeout_fallback")

    /// Lines of terminal history kept in memory
    static let settingsScrollbackSubtitle = LocalizedStringResource("settings_scrollback_subtitle")

    /// Scrollback lines
    static let settingsScrollbackTitle = LocalizedStringResource("settings_scrollback_title")

    /// Backup
    static let settingsSectionBackup = LocalizedStringResource("settings_section_backup")

    /// General
    static let settingsSectionGeneral = LocalizedStringResource("settings_section_general")

    /// Security
    static let settingsSectionSecurity = LocalizedStringResource("settings_section_security")

    /// Terminal
    static let settingsSectionTerminal = LocalizedStringResource("settings_section_terminal")

    /// Keep the suggestion bar at a fixed height to prevent the terminal from resizing when …
    static let settingsSuggestionsBarStickySubtitle = LocalizedStringResource("settings_suggestions_bar_sticky_subtitle")

    /// Always-visible suggestion bar
    static let settingsSuggestionsBarStickyTitle = LocalizedStringResource("settings_suggestions_bar_sticky_title")

    /// Match app theme
    static let settingsTerminalColorsFollowApp = LocalizedStringResource("settings_terminal_colors_follow_app")

    /// Terminal colors
    static let settingsTerminalColorsTitle = LocalizedStringResource("settings_terminal_colors_title")

    /// Dark
    static let settingsThemeDark = LocalizedStringResource("settings_theme_dark")

    /// Follow system
    static let settingsThemeFollowSystem = LocalizedStringResource("settings_theme_follow_system")

    /// Light
    static let settingsThemeLight = LocalizedStringResource("settings_theme_light")

    /// Theme
    static let settingsThemeTitle = LocalizedStringResource("settings_theme_title")

    /// Settings
    static let settingsTitle = LocalizedStringResource("settings_title")

    /// Back to hosts
    static let sftpBackCd = LocalizedStringResource("sftp_back_cd")

    /// Dismiss
    static let sftpBackgroundDismissCd = LocalizedStringResource("sftp_background_dismiss_cd")

    /// Download failed
    static let sftpBackgroundDownloadFailed = LocalizedStringResource("sftp_background_download_failed")

    /// Background downloads
    static let sftpBackgroundDownloadsTitle = LocalizedStringResource("sftp_background_downloads_title")

    /// "%1$@" already exists in Downloads. Download skipped.
    static let sftpBackgroundSkippedExists = LocalizedStringResource("sftp_background_skipped_exists")

    /// %1$d of %2$d files already exist in Downloads. What would you like to do?
    static let sftpBatchConflictMessage = LocalizedStringResource("sftp_batch_conflict_message")

    /// Some files already exist
    static let sftpBatchConflictTitle = LocalizedStringResource("sftp_batch_conflict_title")

    /// %1$d file(s)
    static let sftpBulkDeleteFiles = LocalizedStringResource("sftp_bulk_delete_files")

    /// %1$d folder(s)
    static let sftpBulkDeleteFolders = LocalizedStringResource("sftp_bulk_delete_folders")

    /// You are about to delete:
    static let sftpBulkDeleteMessagePrefix = LocalizedStringResource("sftp_bulk_delete_message_prefix")

    /// Delete selected items
    static let sftpBulkDeleteTitle = LocalizedStringResource("sftp_bulk_delete_title")

    /// Cancelled: %1$@
    static let sftpCancelledAt = LocalizedStringResource("sftp_cancelled_at")

    /// "%1$@" already exists in Downloads/SSHBorg/.
    static let sftpConflictMessage = LocalizedStringResource("sftp_conflict_message")

    /// File already exists
    static let sftpConflictTitle = LocalizedStringResource("sftp_conflict_title")

    /// Delete file
    static let sftpDeleteFileTitle = LocalizedStringResource("sftp_delete_file_title")

    /// Delete folder
    static let sftpDeleteFolderTitle = LocalizedStringResource("sftp_delete_folder_title")

    /// Delete "%1$@"? This cannot be undone.
    static let sftpDeleteMessage = LocalizedStringResource("sftp_delete_message")

    /// This cannot be undone.
    static let sftpDeleteMessageSuffix = LocalizedStringResource("sftp_delete_message_suffix")

    /// Delete selected
    static let sftpDeleteSelectedCd = LocalizedStringResource("sftp_delete_selected_cd")

    /// Deleting:
    static let sftpDeletingLabel = LocalizedStringResource("sftp_deleting_label")

    /// Disconnect
    static let sftpDisconnectCd = LocalizedStringResource("sftp_disconnect_cd")

    /// Disconnected
    static let sftpDisconnected = LocalizedStringResource("sftp_disconnected")

    /// Download
    static let sftpDownloadCd = LocalizedStringResource("sftp_download_cd")

    /// Download complete
    static let sftpDownloadComplete = LocalizedStringResource("sftp_download_complete")

    /// Download folder
    static let sftpDownloadFolderCd = LocalizedStringResource("sftp_download_folder_cd")

    /// Download selected
    static let sftpDownloadSelectedCd = LocalizedStringResource("sftp_download_selected_cd")

    /// Downloaded %1$d files
    static let sftpDownloadedNFiles = LocalizedStringResource("sftp_downloaded_n_files")

    /// Downloaded %1$d files (%2$d skipped)
    static let sftpDownloadedNFilesSkipped = LocalizedStringResource("sftp_downloaded_n_files_skipped")

    /// Downloading:
    static let sftpDownloadingLabel = LocalizedStringResource("sftp_downloading_label")

    /// Empty directory
    static let sftpEmptyDirectory = LocalizedStringResource("sftp_empty_directory")

    /// Finished: %1$@
    static let sftpFinishedAt = LocalizedStringResource("sftp_finished_at")

    /// Delete
    static let sftpMenuDelete = LocalizedStringResource("sftp_menu_delete")

    /// Download in background
    static let sftpMenuDownloadInBackground = LocalizedStringResource("sftp_menu_download_in_background")

    /// Rename
    static let sftpMenuRename = LocalizedStringResource("sftp_menu_rename")

    /// Folder name
    static let sftpMkdirFolderName = LocalizedStringResource("sftp_mkdir_folder_name")

    /// New folder
    static let sftpMkdirTitle = LocalizedStringResource("sftp_mkdir_title")

    /// %1$d selected
    static let sftpNSelected = LocalizedStringResource("sftp_n_selected")

    /// New folder
    static let sftpNewFolderCd = LocalizedStringResource("sftp_new_folder_cd")

    /// Nothing to download
    static let sftpNothingToDownload = LocalizedStringResource("sftp_nothing_to_download")

    /// Preparing…
    static let sftpPreparing = LocalizedStringResource("sftp_preparing")

    /// Refresh
    static let sftpRefreshCd = LocalizedStringResource("sftp_refresh_cd")

    /// New name
    static let sftpRenameNewName = LocalizedStringResource("sftp_rename_new_name")

    /// Rename
    static let sftpRenameTitle = LocalizedStringResource("sftp_rename_title")

    /// Saved: %1$@
    static let sftpSavedToDownloads = LocalizedStringResource("sftp_saved_to_downloads")

    /// Select items
    static let sftpSelectItemsCd = LocalizedStringResource("sftp_select_items_cd")

    /// Background
    static let sftpSendToBackground = LocalizedStringResource("sftp_send_to_background")

    /// Started: %1$@
    static let sftpStartedAt = LocalizedStringResource("sftp_started_at")

    /// Upload complete
    static let sftpUploadComplete = LocalizedStringResource("sftp_upload_complete")

    /// Upload file
    static let sftpUploadFileCd = LocalizedStringResource("sftp_upload_file_cd")

    /// Uploaded: %1$@
    static let sftpUploaded = LocalizedStringResource("sftp_uploaded")

    /// Uploaded %1$d files
    static let sftpUploadedNFiles = LocalizedStringResource("sftp_uploaded_n_files")

    /// Uploading %1$@
    static let sftpUploading = LocalizedStringResource("sftp_uploading")

    /// Connecting…
    static let terminalConnecting = LocalizedStringResource("terminal_connecting")

    /// Connection failed
    static let terminalConnectionFailed = LocalizedStringResource("terminal_connection_failed")

    /// Connection lost
    static let terminalConnectionLost = LocalizedStringResource("terminal_connection_lost")

    /// Copy all
    static let terminalCopyAll = LocalizedStringResource("terminal_copy_all")

    /// Copy error
    static let terminalCopyError = LocalizedStringResource("terminal_copy_error")

    /// Copy selection
    static let terminalCopySelection = LocalizedStringResource("terminal_copy_selection")

    /// Disconnect
    static let terminalDisconnectCd = LocalizedStringResource("terminal_disconnect_cd")

    /// Disconnected
    static let terminalDisconnected = LocalizedStringResource("terminal_disconnected")

    /// Details
    static let terminalErrorDetails = LocalizedStringResource("terminal_error_details")

    /// Paste
    static let terminalPasteCd = LocalizedStringResource("terminal_paste_cd")

    /// Keep key bar visible
    static let terminalPinKeysCd = LocalizedStringResource("terminal_pin_keys_cd")

    /// Terminal
    static let terminalTitleDefault = LocalizedStringResource("terminal_title_default")

    /// 15 minutes
    static let timeout15Minutes = LocalizedStringResource("timeout_15_minutes")

    /// 1 hour
    static let timeout1Hour = LocalizedStringResource("timeout_1_hour")

    /// 1 minute
    static let timeout1Minute = LocalizedStringResource("timeout_1_minute")

    /// 30 minutes
    static let timeout30Minutes = LocalizedStringResource("timeout_30_minutes")

    /// 30 seconds
    static let timeout30Seconds = LocalizedStringResource("timeout_30_seconds")

    /// 3 minutes
    static let timeout3Minutes = LocalizedStringResource("timeout_3_minutes")

    /// 4 hours
    static let timeout4Hours = LocalizedStringResource("timeout_4_hours")

    /// 5 minutes
    static let timeout5Minutes = LocalizedStringResource("timeout_5_minutes")

    /// Immediately
    static let timeoutImmediately = LocalizedStringResource("timeout_immediately")

}
